apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-deployment
  labels:
    app: blockchain
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blockchain
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      containers:
      - image: johnyjantar/capstone-cloud-devops:latest
        imagePullPolicy: Always
        name: blockchain
        ports:
        - containerPort: 5000
          protocol: TCP